### ISSUE TITLE
Can this project be run at IDEA? Or does it have to run on android studio?

### ISSUE THREAD

**Issue by warmingzzz** [libp2p/jvm-libp2p#128]
help！！！

Here's the error I ran on the idea：
A problem occurred evaluating project ':android-chatter'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.4.1. Current version is 5.2.1. If using the gradle wrapper, try editing the distributionUrl in F:\apache-maven-3.6.3-bin\MavenRepository\daemon\5.2.1\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

**Comment by ajsutton** [comment]
It does run in IDEA.  The error message is saying that the version of Gradle being used is too old.  In IntelliJ settings make sure that under `Build, Execution, Deployment` -> `Gradle` that `Use Gradle from` is set to `Gradle-wrapper.properties file` to ensure it uses the right version of Gradle for the project.

And when running from the command line make sure you use `./gradlew` instead of directly executing `gradle` which may be a different version.
