### ISSUE TITLE
test/external: Use rust-libp2p spec compliant `X25519Spec`

### ISSUE THREAD

**Issue by mxinden** [libp2p/jvm-libp2p#260]
https://github.com/libp2p/jvm-libp2p/blob/1e6f17fbb216bcd000551dd413f4a8ec502b0f9f/src/test/external/rust/ping-client/src/main.rs#L13

We are deprecating `X25519`, please use `X25519Spec` instead.

See https://github.com/libp2p/rust-libp2p/pull/3227/.

**Comment by ajsutton** [comment]
hmm, I didn't even know that was there. Those interop tests haven't been running in CI so haven't been maintained and don't seem to be even compiling for the most part.  I've put up a PR to remove them since they don't provide any value if we aren't running them anyway and a simple ping isn't a particularly good compatibility test anyway.

**Comment by mxinden** [comment]
Thanks @ajsutton for the quick response and follow-up!
